name: Publish Docker image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish the Docker image.
    runs-on: ubuntu-latest
    steps:
    # Extract the tag name.
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Check out the repo.
      uses: actions/checkout@v2
    - name: Set up QEMU.
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx.
      uses: docker/setup-buildx-action@v1
    - name: Check out the repo.
      uses: actions/checkout@v2
    - name: Login to Docker Hub.
      uses: docker/login-action@v1.10.0
      with:
        username: ilshidur
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push.
      uses: docker/build-push-action@v2.10.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: ilshidur/zwave-prometheus-exporter:latest,ilshidur/zwave-prometheus-exporter:${{ env.RELEASE_VERSION }}
