name: Publish Docker image

on:
  push:
    branches:
      - main
#  release:
#    types: [published]

jobs:
  build:
    name: Build and publish the Docker image.
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo.
      uses: actions/checkout@v2
    - name: Build the Docker image.
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
    - name: Set up QEMU.
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx.
      uses: docker/setup-buildx-action@v1
    - name: Check out the repo.
      uses: actions/checkout@v2
    - name: Login to Docker Hub.
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push.
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        tags: ${{ github.repository }}:latest
